### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by dpaleino** [mudcube/Color.Picker.js#1]
Hello,

would you please clarify the licensing of Color-Picker projects? "Creative Commons": which one? NC? BY? BY-SA? And which version? (I'd greatly discourage "NC", since that's not compatible with GPL).

The same for "GPL": version 2? Version 3? Specific versions or "2/3 or any later version"?

Thank you very much,
David

**Comment by mudcube** [comment]
Hi, sorry to of missed this message!  I'm sure you've found another solution, but, it's GPL 2/3 and later, and MIT—I'll need to cleanup the licensing files on my projects, as at the time, I didn't quite understand licensing (and still don't entirely).
